'''
PROGRAM TO CHECK IF A GIVEN STRING IS PALINDROME USING RECURSION

ISPALINDROME TAKES A STRING AND RETURNS BOOLEAN 

IF STRINGS LENGTH IS 0 OR 1 RETURN TRUE IS BASECASE
ELSE IF THE FIRST LETTER OF STRING EQUALS LAST LETTER
CALL FUNCTION RECURSIVELY TO SUBSTRING REDUSING ORIGINAL STRING 
BY FIRST AND LAST LETTER IN EACH CALL 

AT LAST IF NOT ,
RETURN FALSE

LET STRING BE ORARO

CALL 1 " ORARO" RETURNS ISPALINDROME("RAR)
CALL 2 "RAR" RETURNS " A"
CALL 3 "A" RETURNS TRUE
STRING IS PALINDROME
'''
def isPalindrome(st):
    if len(st) == 0 or len(st) == 1:
        return True

    if(st[0] == st[-1]):
        return isPalindrome(st[1:len(st) -1])
    return False


print(isPalindrome("apipa"))
